Pass a string to testmd4, so we're unattended Pass some paramters to testdbm, so it actually runs the test
git-svn-id: https://svn.apache.org/repos/asf/apr/apr-util/branches/0.9.x@571767 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/test/Makefile.in b/test/Makefile.in
--- a/test/Makefile.in
+++ b/test/Makefile.in
@@ -19,10 +19,24 @@ all: $(PROGRAMS)
 
 check: $(PROGRAMS)
 	for prog in $(PROGRAMS); do \
-		./$$prog ;\
-		if test $$? = 255; then \
-			echo "$$prog failed"; \
-			break; \
+		if test "$$prog" = 'testmd4'; then \
+			./$$prog -ssomestringtohash; \
+			if test $$? = 255; then \
+				echo "$$prog failed"; \
+				break; \
+			fi; \
+		elif test "$$prog" = 'testdbm'; then \
+			./$$prog auto SDBM; \
+			if test $$? = 255; then \
+				echo "$$prog failed"; \
+				break; \
+			fi; \
+		else \
+			./$$prog ;\
+			if test $$? = 255; then \
+				echo "$$prog failed"; \
+				break; \
+			fi; \
 		fi; \
 	done
 
