Pass driver parameter to dbd test program
git-svn-id: https://svn.apache.org/repos/asf/apr/apr-util/trunk@571754 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/test/Makefile.in b/test/Makefile.in
--- a/test/Makefile.in
+++ b/test/Makefile.in
@@ -22,10 +22,20 @@ LINK_PROG = $(LIBTOOL) $(LTFLAGS) --mode=link $(LT_LDFLAGS) $(COMPILE) @LT_NO_IN
 
 check: $(PROGRAMS)
 	for prog in $(PROGRAMS); do \
-		./$$prog ;\
-		if test $$? = 255; then \
-			echo "$$prog failed"; \
-			break; \
+	        if test "$$prog" = 'dbd'; then \
+			for driver in sqlite2 sqlite3; do \
+				./$$prog $$driver; \
+				if test $$? = 255; then \
+					echo "$$prog $$driver failed"; \
+					break; \
+				fi; \
+			done; \
+	        else \
+			./$$prog; \
+			if test $$? = 255; then \
+				echo "$$prog failed"; \
+				break; \
+			fi; \
 		fi; \
 	done
 
